model_name_or_path: ctheodoris/Geneformer
model_vocab: /content/Geneformer/geneformer/token_dictionary_gc104M.pkl
model_gene_name_dict: /content/Geneformer/geneformer/gene_name_id_dict_gc104M.pkl
tokens_dir: gse131907/processed/tokens
output_dir: outputs/geneformer_lung_base
max_length: 2048
num_epochs: 8
train_batch_size: 8
eval_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
weight_decay: 0.01
patience: 3
seed: 42
label_column: BinaryClass
class_weights:
  Normal: 1.0
  Tumor: 2.05
token_mask_prob: 0.015
mixup_prob: 0.05
mixup_alpha: 0.6
balance_strategy: class_donor
focal_gamma: 1.0
warmup_ratio: 0.1
